### ISSUE TITLE
_apetypes.h is not found on 386

### ISSUE THREAD

**Issue by lufia** [0intro/plan9-contrib#5]
I have applied stable patches, and tried to build ape libs on 386 machine.

`cpp` that was started by `mk all` is exited with errors:

```console
% cd /sys/src/ape/lib
% mk all
...
cpp: /sys/include/ape/stddef.h:15 /sys/include/ape/stdlib.h:5 _buf.c:4 Could not find include file "_apetypes.h"
cpp: /sys/include/ape/inttypes.h:8 _buf.c:5 Could not find include file "_apetypes.h"
```

**Comment by 0intro** [comment]
The `_apetypes.h` file is an empty file on 32-bit machines. Unfortunately, since the file is empty, it's ignored during the creation of the patch. I'll add the creation of these files to this repository's building process in the future.

In the meantime, you have to create the following empty files:

```
touch arm/include/ape/_apetypes.h
touch sparc/include/ape/_apetypes.h
touch power/include/ape/_apetypes.h
touch 386/include/ape/_apetypes.h
touch spim/include/ape/_apetypes.h
touch mips/include/ape/_apetypes.h
```

Also, due to the limitations of Git, you'll also need to create various empty directories. There is a [mkdirs](http://www.9legacy.org/9legacy/tools/mkdirs) script available to create them.

**Comment by lufia** [comment]
Thank you for your advice.
I've updated my tool, to create empty files.

**Comment by 0intro** [comment]
Very nice! Thanks for your work on these tools!
